name: deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Pull on and restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VWIS_HOST }}
        username: ${{ secrets.VWIS_USERNAME }}
        key: ${{ secrets.VWIS_KEY }}
        passphrase: ${{ secrets.VWIS_PASSPHRASE }}
        script: |
          # print info
          whoami

          # go to repo dir
          cd /home/vovveti2/public_html/vasistart/vasistartserver

          # enable venv
          source /home/vovveti2/virtualenv/public_html/vasistart/vasistartserver/3.8/bin/activate

          # update
          git fetch
          git reset --hard origin/main

          # Install new requirements
          pip install --upgrade -r requirements.txt

          # restart server
          touch ./tmp/restart.txt
